### ISSUE TITLE
pushetta stopped working on raspberry pi [SOLVED]

### ISSUE THREAD

**Issue by m3fisto** [guglielmino/pushetta-py#4]
Hi and thanks a lot for your wonderful project!
I am using pushetta for a couple of months for an burglar alarm notification system and it worked fine until a couple of weeks ago when I discovered that it no longer worked.
running this simple script 

```
from pushetta import Pushetta

API_KEY="..."
CHANNEL_NAME="..."
p=Pushetta(API_KEY)
p.pushMessage(CHANNEL_NAME, "Hello World")
```

I get:

```

Traceback (most recent call last):
  File "test_pushetta.py", line 1, in <module>
    from pushetta import Pushetta
  File "/usr/local/lib/python2.7/dist-packages/pushetta/__init__.py", line 2, in <module>
    from .pushetta import Pushetta
  File "/usr/local/lib/python2.7/dist-packages/pushetta/pushetta.py", line 40, in <module>
    import urllib
  File "/usr/lib/python2.7/urllib.py", line 850, in <module>
    class ftpwrapper:
  File "/usr/lib/python2.7/urllib.py", line 854, in ftpwrapper
    timeout=socket._GLOBAL_DEFAULT_TIMEOUT,
AttributeError: 'module' object has no attribute '_GLOBAL_DEFAULT_TIMEOUT'
```

I tried uninstalling-reinstalling pushetta via pip several times with no luck

Any ideas?
Thanks a lot in advance!

**Comment by guglielmino** [comment]
Hi,
Some days ago we changed server and ip for Pushetta services, looking at stack trace of error it seems a connection timeout problem. Is there a firewall in your connection? May be it blocks for some reason connection to new server's address.

**Comment by m3fisto** [comment]
Hi 
Unfortunately even when I disabled all firewall the problem persisted.
Thanks a lot for your answer though!!

BRs
Paris

**Comment by guglielmino** [comment]
Check if this can solve Your problem http://stackoverflow.com/questions/20546491/global-default-timeout-occurs-on-simple-urlopen
Il giorno 21 marzo 2016 @ 13:55:07, m3fisto (notifications@github.com) ha scritto:

Hi
Unfortunately even when I disabled all firewall the problem persisted.
Thanks a lot for your answer though!!

BRs
Paris

**Comment by m3fisto** [comment]
SOLVED!!!!

As the guys above mentioned , all I had to do was to delete socket.py and socket.pyc from the folder I was running my script

Thanks a lot for the support
