### ISSUE TITLE
I can´t import pushetta

### ISSUE THREAD

**Issue by Ecastillo12** [guglielmino/pushetta-py#7]
I have the example:

from pushetta import Pushetta

API_KEY="00112233445566778899aabbccddeeff00112233"
p=Pushetta(API_KEY)
p.pushMessage("raspi", "Hello World")

I replace my API Key and my channel, but I got the error:
Traceback (most recent call last):
  File "prueba.py", line 1, in <module>
    from pushetta import Pushetta
  File "C:\Users\E_Cas\OneDrive\Documentos\PRACTICA\pushetta.py", line 1, in <module>
ImportError: cannot import name Pushetta

**Comment by guglielmino** [comment]
Did you install pushetta before running the script? I mean `pip install pushetta`

**Comment by Ecastillo12** [comment]
Yes I did, but i solved it. The problem was an old python installation, I just deleted the folders and reinstalled python, then reinstalled the library. Anyway Thanks! 👍

**Comment by guglielmino** [comment]
Ok, that’s fine
